apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-order-svc
  labels:
    app: {{ .Release.Name }}-order-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-order-svc
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-order-svc
    spec:
      containers:
      - name: order-svc
        image: {{ .Values.images.orderService }}
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 8000
        env:
        - name: KAFKA_HOST
          value: {{ printf "%s-%s" .Release.Name "cp-kafka" }}
        - name: POSTGRES_0_HOST
          value: {{ printf "%s-%s" .Release.Name "postgres0" }}
        - name: POSTGRES_0_PORT
          value: "5432"
        - name: POSTGRES_0_DB
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: postgresDbName
        - name: POSTGRES_0_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: postgresUsername
        - name: POSTGRES_0_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: postgresPass
        - name: POSTGRES_1_HOST
          value: {{ printf "%s-%s" .Release.Name "postgres1" }}
        - name: POSTGRES_1_PORT
          value: "5432"
        - name: POSTGRES_1_DB
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: postgres1DbName
        - name: POSTGRES_1_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: postgres1Username
        - name: POSTGRES_1_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: postgres1Pass

        readinessProbe:
          httpGet:
            port: 8000
            path: /health
          initialDelaySeconds: 2
          periodSeconds: 5
