host: arch.homework
appPathPrefix: /otusapp

images:
  authService: dachdev/otus-architect:hw15-auth-service
  productService: dachdev/otus-architect:hw15-product-service
  productDbInit: dachdev/otus-architect:hw15-product-db-init
  userService: dachdev/otus-architect:hw15-user-service
  userDbInit: dachdev/otus-architect:hw15-user-db-init

product:
  cache:
    enabled: true

metrics:
  enabled: true

postgresql:
  postgresqlUsername: dach
  postgresqlPassword: dach
  postgresqlDatabase: dach
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

redis:
  password: dach
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  master:
    extraFlags:
      - "--maxmemory-policy volatile-lru"