apiVersion: v3
name: dach-hw09-user-svc-chart
description: A Helm chart for Otus Architect HW09. User service

type: application

version: 0.0.1
appVersion: 0.0.1

dependencies:
  - name: postgresql
    version: 8.7.2
    repository: "@bitnami"
