apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-delivery-svc
  labels:
    app: {{ .Release.Name }}-delivery-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-delivery-svc
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-delivery-svc
    spec:
      containers:
      - name: delivery-svc
        image: {{ .Values.images.deliveryService }}
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          value: {{ printf "%s-%s" .Release.Name "postgresql" }}
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: postgresDbName
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: postgresUsername
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: postgresPass
        - name: KAFKA_HOST
          value: {{ printf "%s-%s" .Release.Name "cp-kafka" }}
        - name: ORDER_SVC_ADDRESS
          value: "http://{{ .Release.Name }}-order-svc.default.svc.cluster.local:8000"
        readinessProbe:
          httpGet:
            port: 8000
            path: /health
          initialDelaySeconds: 2
          periodSeconds: 5
