apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-stress-test-job
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: {{ .Release.Name }}-stress-test
        image: {{ .Values.images.stressTest }}
        args: ["-o", "phantom.address={{ .Values.ingressAddress }}"]
      restartPolicy: Never