apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/auth-url: "{{ .Values.serviceAddress.authService }}/auth"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Username"
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: {{ .Values.appPathPrefix }}(.*)
        pathType: Prefix
        backend:
          serviceName: {{ .Release.Name }}-user-svc
          servicePort: 8000
