apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-auth-svc
  labels:
    app: {{ .Release.Name }}-auth-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-auth-svc
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-auth-svc
    spec:
      containers:
      - name: auth-svc
        image: {{ .Values.images.authService }}
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 8000
        env:
        - name: USER_SVC_ADDRESS
          value: "http://{{ .Release.Name }}-user-svc.default.svc.cluster.local:8000"
        - name: AUTH_DOMAIN
          value: {{ .Values.host }}
        readinessProbe:
          httpGet:
            port: 8000
            path: /health
          initialDelaySeconds: 2
          periodSeconds: 5
