apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-auth-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: {{ .Values.appPathPrefix }}/auth(.*)
        pathType: Prefix
        backend:
          serviceName: {{ .Release.Name }}-auth-svc
          servicePort: 8000
