apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth-svc
  labels:
    app: {{ .Release.Name }}-auth-svc
    otusappRelease: {{ .Release.Name }}
    otusappMonitoring: "true"
spec:
  selector:
    app: {{ .Release.Name }}-auth-svc
  ports:
    - name: web
      protocol: TCP
      port: 8000
      targetPort: 8000 
  type: NodePort
