{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-auth-svc-monitor
spec:
  jobLabel: {{ .Release.Name }}-auth-svc-monitor
  namespaceSelector:
    matchNames:
    - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      app: {{ .Release.Name }}-auth-svc
  endpoints:
  - interval: 15s
    port: web
    path: /metrics
{{- end }}     