apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  postgresDbName: {{ .Values.postgresql.postgresqlDatabase | quote }}
  postgresUsername: {{ .Values.postgresql.postgresqlUsername | quote }}
  productCacheEnabled: {{ .Values.product.cache.enabled | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  postgresPass: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  redisPass: {{ .Values.redis.password | b64enc | quote }}